# Introduction of Machine Learning

In [1]:
import pandas as pd

In [2]:
data2 = pd.read_csv('Titanic_data_cleaned.csv')

In [3]:
data2

Unnamed: 0  PassengerId Survived  Pclass     Sex  Age  \
0             0          343       No       2    male   28   
1             1           76       No       3    male   25   
2             2          641       No       3    male   20   
3             3          568       No       3  female   29   
4             4          672       No       1    male   31   
..          ...          ...      ...     ...     ...  ...   
886         886           10      Yes       2  female   14   
887         887           61       No       3    male   22   
888         888          535       No       3  female   30   
889         889          102       No       3    male   29   
890         890          428      Yes       2  female   19   

     Siblings and spanous  parent and child      Ticket     Fare Embarked  \
0                       0                 0      248740  13.0000        S   
1                       0                 0      348123   7.6500        S   
2                       0                 0      350050   7.8542        S   
3                       0                 4      349909  21.0750        S   
4                       1                 0  F.C. 12750  52.0000        S   
..                    ...               ...         ...      ...      ...   
886                     1                 0      237736  30.0708        C   
887                     0                 0        2669   7.2292        C   
888                     0                 0      315084   8.6625        S   
889                     0                 0      349215   7.8958        S   
890                     0                 0      250655  26.0000        S   

                                                  Name  
0                              Mr.Erik GustafCollander  
1                                 Mr.Sigurd HansenMoen  
2                                  Mr.Hans PederJensen  
3               Mrs.Nils Alma Cornelia BerglundPalsson  
4                                  Mr.ThorntonDavidson  
..                                                 ...  
886                     Mrs.Nicholas Adele AchemNasser  
887                                 Mr.OrsenSirayanian  
888                                   Miss.MarijaCacic  
889                          Mr.Pastcho PentchoPetroff  
890  Miss.Kate Florence Mrs Kate Louise Phillips Ma...  

[891 rows x 12 columns]

In [4]:
data2 = data2.drop('Unnamed: 0', axis=1) #data2.drop(''Unnamed: 0', inplace = False axis=1')

In [5]:
data2

PassengerId Survived  Pclass     Sex  Age  Siblings and spanous  \
0            343       No       2    male   28                     0   
1             76       No       3    male   25                     0   
2            641       No       3    male   20                     0   
3            568       No       3  female   29                     0   
4            672       No       1    male   31                     1   
..           ...      ...     ...     ...  ...                   ...   
886           10      Yes       2  female   14                     1   
887           61       No       3    male   22                     0   
888          535       No       3  female   30                     0   
889          102       No       3    male   29                     0   
890          428      Yes       2  female   19                     0   

     parent and child      Ticket     Fare Embarked  \
0                   0      248740  13.0000        S   
1                   0      348123   7.6500        S   
2                   0      350050   7.8542        S   
3                   4      349909  21.0750        S   
4                   0  F.C. 12750  52.0000        S   
..                ...         ...      ...      ...   
886                 0      237736  30.0708        C   
887                 0        2669   7.2292        C   
888                 0      315084   8.6625        S   
889                 0      349215   7.8958        S   
890                 0      250655  26.0000        S   

                                                  Name  
0                              Mr.Erik GustafCollander  
1                                 Mr.Sigurd HansenMoen  
2                                  Mr.Hans PederJensen  
3               Mrs.Nils Alma Cornelia BerglundPalsson  
4                                  Mr.ThorntonDavidson  
..                                                 ...  
886                     Mrs.Nicholas Adele AchemNasser  
887                                 Mr.OrsenSirayanian  
888                                   Miss.MarijaCacic  
889                          Mr.Pastcho PentchoPetroff  
890  Miss.Kate Florence Mrs Kate Louise Phillips Ma...  

[891 rows x 11 columns]

In [6]:
### standardization
### tokenization 
### lemmatization
### encoding
### Reshape
### Bias
### Parameter
### inferential stat
### text corpose
### over sampling
### under sampling
### x_train, x_test, y_train, y_test
### trialier and exception

In [7]:
data2

PassengerId Survived  Pclass     Sex  Age  Siblings and spanous  \
0            343       No       2    male   28                     0   
1             76       No       3    male   25                     0   
2            641       No       3    male   20                     0   
3            568       No       3  female   29                     0   
4            672       No       1    male   31                     1   
..           ...      ...     ...     ...  ...                   ...   
886           10      Yes       2  female   14                     1   
887           61       No       3    male   22                     0   
888          535       No       3  female   30                     0   
889          102       No       3    male   29                     0   
890          428      Yes       2  female   19                     0   

     parent and child      Ticket     Fare Embarked  \
0                   0      248740  13.0000        S   
1                   0      348123   7.6500        S   
2                   0      350050   7.8542        S   
3                   4      349909  21.0750        S   
4                   0  F.C. 12750  52.0000        S   
..                ...         ...      ...      ...   
886                 0      237736  30.0708        C   
887                 0        2669   7.2292        C   
888                 0      315084   8.6625        S   
889                 0      349215   7.8958        S   
890                 0      250655  26.0000        S   

                                                  Name  
0                              Mr.Erik GustafCollander  
1                                 Mr.Sigurd HansenMoen  
2                                  Mr.Hans PederJensen  
3               Mrs.Nils Alma Cornelia BerglundPalsson  
4                                  Mr.ThorntonDavidson  
..                                                 ...  
886                     Mrs.Nicholas Adele AchemNasser  
887                                 Mr.OrsenSirayanian  
888                                   Miss.MarijaCacic  
889                          Mr.Pastcho PentchoPetroff  
890  Miss.Kate Florence Mrs Kate Louise Phillips Ma...  

[891 rows x 11 columns]

In [8]:
data2.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Sex', 'Age',
       'Siblings and spanous', 'parent and child', 'Ticket', 'Fare',
       'Embarked', 'Name'],
      dtype='object')

In [9]:
data2.drop(columns = ['Embarked', 'Name', 'Ticket', 'PassengerId'], inplace = True, axis = 1)

In [10]:
data2

Survived  Pclass     Sex  Age  Siblings and spanous  parent and child  \
0         No       2    male   28                     0                 0   
1         No       3    male   25                     0                 0   
2         No       3    male   20                     0                 0   
3         No       3  female   29                     0                 4   
4         No       1    male   31                     1                 0   
..       ...     ...     ...  ...                   ...               ...   
886      Yes       2  female   14                     1                 0   
887       No       3    male   22                     0                 0   
888       No       3  female   30                     0                 0   
889       No       3    male   29                     0                 0   
890      Yes       2  female   19                     0                 0   

        Fare  
0    13.0000  
1     7.6500  
2     7.8542  
3    21.0750  
4    52.0000  
..       ...  
886  30.0708  
887   7.2292  
888   8.6625  
889   7.8958  
890  26.0000  

[891 rows x 7 columns]

In [11]:
data2['Survived'] = data2['Survived'].replace({'Yes': 1, 'No': 0})
data2['Sex'] = data2['Sex'].replace({'male': 1, 'female': 0})

In [12]:
data2

Survived  Pclass  Sex  Age  Siblings and spanous  parent and child  \
0           0       2    1   28                     0                 0   
1           0       3    1   25                     0                 0   
2           0       3    1   20                     0                 0   
3           0       3    0   29                     0                 4   
4           0       1    1   31                     1                 0   
..        ...     ...  ...  ...                   ...               ...   
886         1       2    0   14                     1                 0   
887         0       3    1   22                     0                 0   
888         0       3    0   30                     0                 0   
889         0       3    1   29                     0                 0   
890         1       2    0   19                     0                 0   

        Fare  
0    13.0000  
1     7.6500  
2     7.8542  
3    21.0750  
4    52.0000  
..       ...  
886  30.0708  
887   7.2292  
888   8.6625  
889   7.8958  
890  26.0000  

[891 rows x 7 columns]

In [13]:
# alternative for formula for Encoding
# from sklearn.preprocessing import LabelEncoder

#le = LabelEncoder()
#data2[''] = le.fit_transform(data2[''])

In [14]:
from sklearn.preprocessing import StandardScaler
import numpy as np

sc = StandardScaler()
data2['Fare'] = sc.fit_transform(np.array(data2['Fare']).reshape(-1, 1))

In [15]:
data2

Survived  Pclass  Sex  Age  Siblings and spanous  parent and child  \
0           0       2    1   28                     0                 0   
1           0       3    1   25                     0                 0   
2           0       3    1   20                     0                 0   
3           0       3    0   29                     0                 4   
4           0       1    1   31                     1                 0   
..        ...     ...  ...  ...                   ...               ...   
886         1       2    0   14                     1                 0   
887         0       3    1   22                     0                 0   
888         0       3    0   30                     0                 0   
889         0       3    1   29                     0                 0   
890         1       2    0   19                     0                 0   

         Fare  
0   -0.386671  
1   -0.494391  
2   -0.490280  
3   -0.224083  
4    0.398582  
..        ...  
886 -0.042956  
887 -0.502864  
888 -0.474005  
889 -0.489442  
890 -0.124920  

[891 rows x 7 columns]

In [16]:
data2['Survived'] = data2['Survived'].replace({1:'Yes', 0:'No'})   # changing number to text
data2['Sex'] = data2['Sex'].replace({1:'male', 0:'female'})

In [17]:
data2

Survived  Pclass     Sex  Age  Siblings and spanous  parent and child  \
0         No       2    male   28                     0                 0   
1         No       3    male   25                     0                 0   
2         No       3    male   20                     0                 0   
3         No       3  female   29                     0                 4   
4         No       1    male   31                     1                 0   
..       ...     ...     ...  ...                   ...               ...   
886      Yes       2  female   14                     1                 0   
887       No       3    male   22                     0                 0   
888       No       3  female   30                     0                 0   
889       No       3    male   29                     0                 0   
890      Yes       2  female   19                     0                 0   

         Fare  
0   -0.386671  
1   -0.494391  
2   -0.490280  
3   -0.224083  
4    0.398582  
..        ...  
886 -0.042956  
887 -0.502864  
888 -0.474005  
889 -0.489442  
890 -0.124920  

[891 rows x 7 columns]

In [18]:
data2['Survived'] = data2['Survived'].replace({'Yes': 1, 'No': 0})  # changing text to number 
data2['Sex'] = data2['Sex'].replace({'male': 1, 'female': 0})

In [19]:
data2

Survived  Pclass  Sex  Age  Siblings and spanous  parent and child  \
0           0       2    1   28                     0                 0   
1           0       3    1   25                     0                 0   
2           0       3    1   20                     0                 0   
3           0       3    0   29                     0                 4   
4           0       1    1   31                     1                 0   
..        ...     ...  ...  ...                   ...               ...   
886         1       2    0   14                     1                 0   
887         0       3    1   22                     0                 0   
888         0       3    0   30                     0                 0   
889         0       3    1   29                     0                 0   
890         1       2    0   19                     0                 0   

         Fare  
0   -0.386671  
1   -0.494391  
2   -0.490280  
3   -0.224083  
4    0.398582  
..        ...  
886 -0.042956  
887 -0.502864  
888 -0.474005  
889 -0.489442  
890 -0.124920  

[891 rows x 7 columns]

In [20]:
data2.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'Siblings and spanous',
       'parent and child', 'Fare'],
      dtype='object')

In [21]:
data2 = data2.rename(columns={'Siblings and spanous': 'Siblings_spanous', 
                              'parent and child': 'parent_child'})

In [22]:
x = data2 [['Pclass', 'Sex', 'Age', 'Siblings_spanous', 'parent_child', 'Fare']]
y = data2 ['Survived']

In [23]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 40)

In [24]:
x_train

Pclass  Sex  Age  Siblings_spanous  parent_child      Fare
661       1    1   27                 1             0  0.420730
393       2    0   22                 1             1 -0.064516
266       2    1   36                 0             2 -0.124920
144       2    1   62                 0             0 -0.437007
446       1    0   29                 0             0  3.606793
..      ...  ...  ...               ...           ...       ...
440       1    1   54                 0             1  0.907738
165       3    1    9                 4             2 -0.016444
7         3    0    1                 0             2 -0.331467
219       2    0   44                 1             0 -0.124920
326       1    0   29                 1             0  1.145664

[712 rows x 6 columns]

In [25]:
x_test

Pclass  Sex  Age  Siblings_spanous  parent_child      Fare
246       3    1   28                 2             0 -0.488854
588       1    1   71                 0             0  0.049330
472       1    0   19                 1             0  1.185430
71        3    0   19                 0             0 -0.489776
654       3    1   30                 0             0 -0.502445
..      ...  ...  ...               ...           ...       ...
284       1    0   33                 1             0  1.163700
727       1    0   49                 1             0  0.896497
599       3    0   29                 0             2 -0.341452
525       3    0    2                 0             1 -0.401017
457       1    1   33                 0             0 -0.547748

[179 rows x 6 columns]

In [26]:
y_train

661    1
393    1
266    0
144    1
446    1
      ..
440    0
165    0
7      1
219    0
326    1
Name: Survived, Length: 712, dtype: int64

In [27]:
y_test

246    0
588    0
472    1
71     1
654    0
      ..
284    1
727    1
599    1
525    1
457    0
Name: Survived, Length: 179, dtype: int64

In [28]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(x_train, y_train)

LogisticRegression()

In [29]:
computer_prediction = model.predict(x_test)

In [30]:
computer_prediction

array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0], dtype=int64)

In [31]:
np.array(y_test)

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0], dtype=int64)

In [32]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(computer_prediction, y_test)

In [33]:
accuracy

0.770949720670391

In [34]:
from sklearn.metrics import f1_score

f1 = f1_score(computer_prediction, y_test)

In [35]:
f1

0.7007299270072993

In [36]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(computer_prediction, y_test)

In [37]:
cm

array([[90, 23],
       [18, 48]], dtype=int64)

In [38]:
from sklearn.metrics import r2_score

R2 = r2_score(computer_prediction, y_test)

In [39]:
R2

0.01595602038079924

In [40]:
data2.corr()

Survived    Pclass       Sex       Age  Siblings_spanous  \
Survived          1.000000 -0.338481 -0.543351 -0.067809         -0.035322   
Pclass           -0.338481  1.000000  0.131900 -0.335071          0.083081   
Sex              -0.543351  0.131900  1.000000  0.082533         -0.114631   
Age              -0.067809 -0.335071  0.082533  1.000000         -0.232743   
Siblings_spanous -0.035322  0.083081 -0.114631 -0.232743          1.000000   
parent_child      0.081629  0.018443 -0.245489 -0.176744          0.414838   
Fare              0.257307 -0.549500 -0.182333  0.093856          0.159651   

                  parent_child      Fare  
Survived              0.081629  0.257307  
Pclass                0.018443 -0.549500  
Sex                  -0.245489 -0.182333  
Age                  -0.176744  0.093856  
Siblings_spanous      0.414838  0.159651  
parent_child          1.000000  0.216225  
Fare                  0.216225  1.000000

In [41]:
# decision tree

In [42]:
from sklearn.tree import DecisionTreeClassifier

DTC = DecisionTreeClassifier()
DTC.fit(x_train, y_train)

DecisionTreeClassifier()

In [43]:
result = DTC.predict(x_test)

In [44]:
result

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0], dtype=int64)

In [45]:
np.array(y_test)

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0], dtype=int64)

In [46]:
from sklearn.metrics import accuracy_score

DTC_accuracy = accuracy_score(result, y_test)

In [47]:
DTC_accuracy

0.7988826815642458

In [48]:
from sklearn.metrics import f1_score

f2 = f1_score(result, y_test)

In [49]:
f2

0.7534246575342466

In [50]:
from sklearn.ensemble import RandomForestClassifier

RFC = RandomForestClassifier()
RFC.fit(x_train, y_train)

RandomForestClassifier()

In [51]:
RFC_result = RFC.predict(x_test)

In [52]:
RFC_result

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0], dtype=int64)

In [53]:
np.array(y_test)

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0], dtype=int64)

In [54]:
from sklearn.metrics import accuracy_score

RFC_accuracy = accuracy_score(RFC_result, y_test)

In [55]:
RFC_accuracy

0.7877094972067039

In [56]:
from sklearn.neighbors import KNeighborsClassifier

KNC = KNeighborsClassifier()
KNC.fit(x_train, y_train)

KNeighborsClassifier()

In [57]:
KNC_result = KNC.predict(x_test)

In [58]:
KNC_result

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1], dtype=int64)

In [59]:
np.array(y_test)

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0], dtype=int64)

In [60]:
from sklearn.metrics import accuracy_score

KNC_accuracy = accuracy_score(KNC_result, y_test)

In [61]:
KNC_accuracy

0.7653631284916201

In [62]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(x_train, y_train)

SVC()

In [63]:
svc_result = svc.predict(x_test)

In [64]:
svc_result

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0], dtype=int64)

In [65]:
np.array(y_test)

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0], dtype=int64)

In [66]:
from sklearn.metrics import accuracy_score

svc_accuracy = accuracy_score(svc_result, y_test)

In [67]:
svc_accuracy

0.6536312849162011

In [68]:
from sklearn.naive_bayes import GaussianNB

GNB = GaussianNB()
GNB.fit(x_train, y_train)

GaussianNB()

In [69]:
GNB_result = GNB.predict(x_test)

In [70]:
GNB_result

array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0], dtype=int64)

In [71]:
np.array(y_test)

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0], dtype=int64)

In [72]:
from sklearn.metrics import accuracy_score

GNB_accuracy = accuracy_score(GNB_result, y_test)

In [73]:
GNB_accuracy

0.776536312849162

In [74]:
print('Enter correct username and password combo to continue')
count = 0

# "" or '' because you are assigning a value string into it
password = ""
username = ""

# looping will continue when wrong input for three times and ask again...
while password!='Hytu76E' and username!='bank_admin' and count < 3:
    # you are collecting user input from CLI separately (you can not assign and operator to such operation as per your code ;)
    username = input("Enter username: ")
    password = input("Enter password: ")

    if password=='Hytu76E' and username=='bank_admin':
     # if match, grand and break
     print('Access granted')
     break

    else:
        print('Access denied. Try again.')
        count+=1     # as per gbse, in the comments, you will need the + to count up

Enter correct username and password combo to continue


Enter username:  bank_admin
Enter password:  Hytu76E


Access granted


In [75]:
print('Enter correct username and password combo to continue')
count = 0

# Correct username and password
correct_username = 'bank_admin'
correct_password = 'Hytu76E'

# Loop until the correct credentials are entered or the count reaches 3
while count < 3:
    # Collect user input from CLI
    username = input("Enter username: ")
    password = input("Enter password: ")

    # Check if the entered credentials match the correct ones
    if password == correct_password and username == correct_username:
        print('Access granted')
        break  # Exit the loop if access is granted
    else:
        print('Access denied. Try again.')
        count += 1  # Increment the count of failed attempts

# If the loop ends due to reaching the maximum number of attempts
if count == 3:
    print('Maximum number of attempts reached. Access denied.')

Enter correct username and password combo to continue


Enter username:  bank_admin
Enter password:  Hytu76E


Access granted


In [76]:
import re

trials = 0

pwd = 2021

pat = "\d{4}"

while trials <= 2:
   	try:
   		t = int(input("Enter password: "))
   		if t == pwd:
   			print("access granted")
   			break
   		elif re.search(pat, str(t)) == None:
   			print("only 4 digits allowed!")
   			trials += 1
   			print("Trial N°", trials)
   		else:
   			print("Access denied")
   			trials += 1
   			print("Trial N°", trials)
   	
   	except ValueError:
   		print("Invalid input! only digits allowed!")
   		trials += 1
   		print("Trial N°", trials)


Enter password:  2021


access granted


In [77]:
data = {'first_name': ['blessing', 'joseph', 'kaite', 'oye', 'bose'], 
        'last_name': ['john', 'patrick', 'tunde', 'emeka', 'seun'], 
        'age': [30, 20, 78, 54, 76], 
        'job_role': ['data analysis', 'reception', 'banker', 'teacher', 'secruity'], 
        'salary': [500000, 300000, 700000, 400000, 600000],
       'Nationality' : ['nigeria', 'south africa', 'togo', 'uk,', 'usa']}

In [78]:
import pandas as pd

In [79]:
Employer = pd.DataFrame(data)

In [80]:
Employer

first_name last_name  age       job_role  salary   Nationality
0   blessing      john   30  data analysis  500000       nigeria
1     joseph   patrick   20      reception  300000  south africa
2      kaite     tunde   78         banker  700000          togo
3        oye     emeka   54        teacher  400000           uk,
4       bose      seun   76       secruity  600000           usa

In [81]:
x

Pclass  Sex  Age  Siblings_spanous  parent_child      Fare
0         2    1   28                 0             0 -0.386671
1         3    1   25                 0             0 -0.494391
2         3    1   20                 0             0 -0.490280
3         3    0   29                 0             4 -0.224083
4         1    1   31                 1             0  0.398582
..      ...  ...  ...               ...           ...       ...
886       2    0   14                 1             0 -0.042956
887       3    1   22                 0             0 -0.502864
888       3    0   30                 0             0 -0.474005
889       3    1   29                 0             0 -0.489442
890       2    0   19                 0             0 -0.124920

[891 rows x 6 columns]

In [82]:
#x.columns

In [83]:
x

Pclass  Sex  Age  Siblings_spanous  parent_child      Fare
0         2    1   28                 0             0 -0.386671
1         3    1   25                 0             0 -0.494391
2         3    1   20                 0             0 -0.490280
3         3    0   29                 0             4 -0.224083
4         1    1   31                 1             0  0.398582
..      ...  ...  ...               ...           ...       ...
886       2    0   14                 1             0 -0.042956
887       3    1   22                 0             0 -0.502864
888       3    0   30                 0             0 -0.474005
889       3    1   29                 0             0 -0.489442
890       2    0   19                 0             0 -0.124920

[891 rows x 6 columns]

In [84]:
import joblib

joblib.dump(model, 'Titanic_model_lr.model')

['Titanic_model_lr.model']